Repository Xian55/WowClassicGrindBot, pull requests merged in 2022-08, with the labels that each got.

#361 Addon: [1.6.1] - "WhenUsable" - Add support for Warrior 'Victory Rush' ability.
  Addons/DataToColor/DataToColor.lua
  Addons/DataToColor/DataToColor.toc
  Addons/DataToColor/Query.lua
  Addons/DataToColor/Storage.lua
Labels: enhancement

#364 Fix: reduce the probability of `Object is currently in use elsewhere` when accessing bitmap on Frontend thread.
  SharedLib/NpcFinder/NpcNameFinder.cs
Labels: bugfix

#368 Make x64 bit build possible - using platform dependent `StormLib.dll`
  BlazorServer/BlazorServer.csproj
  Core/Core.csproj
  CoreTests/CoreTests.csproj
  DataConfig/DataConfig.csproj
  Frontend/Frontend.csproj
  Game/Game.csproj
  HeadlessServer/HeadlessServer.csproj
  MasterOfPuppets.sln
  PPather/MPQ/StormLib.dll
  PPather/MPQ/StormLib_x64.dll
  PPather/MPQ/StormLib_x86.dll
  PPather/PPather.csproj
  PPather/Triangles/StormDll.cs
  PathingAPI/PathingAPI.csproj
  SharedLib/SharedLib.csproj
  WinAPI/WinAPI.csproj
  WowheadDB/WowheadDB.csproj
Labels: enhancement, breaking change

#375 Addon: [1.6.3] - Feature: Tracking Target buffs duration - `AuraTimeReader` keep tracks of unlimited duration times as well.
  Addons/DataToColor/Collections.lua
  Addons/DataToColor/DataToColor.lua
  Addons/DataToColor/DataToColor.toc
  Addons/DataToColor/Query.lua
  Core/Addon/AddonReader.cs
  Core/Addon/AuraTimeReader.cs
  Core/ClassConfig/ClassConfiguration.cs
  Core/Requirement/RequirementFactory.cs
  README.md
Labels: documentation, enhancement

#377 Core: Added 'Wait' Sequence to ClassConfiguration.
  Core/Actionbar/ActionBarPopulator.cs
  Core/Bag/BagReader.cs
  Core/ClassConfig/ClassConfiguration.cs
  Core/ClassConfig/KeyAction.cs
  Core/ClassConfig/KeyActions.cs
  Core/Goals/ConditionalWaitGoal.cs
  Core/GoalsFactory/GoalFactory.cs
  Core/Requirement/RequirementFactory.cs
  README.md
Labels: documentation, enhancement

#379 Refactor: `PPather` remove unused double caches. A* obstacle avoidance path gen improvements
  PPather/Graph/GraphChunk.cs
  PPather/Graph/PathGraph.cs
  PPather/Graph/Spot.cs
  PPather/Search/MeshFactory.cs
  PPather/Search/PPatherService.cs
  PPather/Search/Search.cs
  PPather/Triangles/ChunkAddedEventArgs.cs
  PPather/Triangles/ChunkEventArgs.cs
  PPather/Triangles/ChunkedTriangleCollection.cs
  PPather/Triangles/Data/Matrix4.cs
  PPather/Triangles/Data/QuadArray.cs
  PPather/Triangles/Data/SparseFloatMatrix2D.cs
  PPather/Triangles/Data/SparseFloatMatrix3D.cs
  PPather/Triangles/Data/SparseMatrix2D.cs
  PPather/Triangles/Data/SparseMatrix3D.cs
  PPather/Triangles/Data/TrioArray.cs
  PPather/Triangles/MPQTriangleSupplier.cs
  PPather/Triangles/TriangleCollection.cs
  PPather/Triangles/TriangleMatrix.cs
  PPather/Triangles/Utils.cs
  PathingAPI/Pages/SearchParameters.razor
  PathingAPI/Pages/Watch.razor
Labels: refactor, enhancement

#382 Feature: Obtain target `UnitClassification`
  Addons/DataToColor/DataToColor.lua
  Addons/DataToColor/DataToColor.toc
  Addons/DataToColor/Query.lua
  Core/Addon/PlayerReader.cs
  Core/AddonComponent/AddonBits.cs
  Core/AddonComponent/UnitClassification.cs
  Core/ClassConfig/ClassConfiguration.cs
  Core/GoalsComponent/Blacklist/Blacklist.cs
  Core/Requirement/RequirementFactory.cs
  Frontend/Pages/BotHeader.razor
  README.md
  SharedLib/Extensions/EnumExtension.cs
Labels: documentation, bugfix, refactor, enhancement

#386 Addon: [1.7.1] - Simplify: Math formulas - Cost and Cooldown minor fixes - Wrath Cat Actionbar - Added unit based Range checks
  Addons/DataToColor/Constants.lua
  Addons/DataToColor/DataToColor.lua
  Addons/DataToColor/DataToColor.toc
  Addons/DataToColor/Query.lua
  Addons/DataToColor/Storage.lua
  Core/Actionbar/ActionBar.cs
  Core/Actionbar/ActionBarCooldownReader.cs
  Core/Actionbar/ActionBarCostReader.cs
  Core/Addon/AddonReader.cs
  Core/Addon/ConfigAddonReader.cs
  Core/Addon/IAddonReader.cs
  Core/Addon/PlayerReader.cs
  Core/AddonComponent/AddonBits.cs
  Core/AddonComponent/SpellInRange.cs
  Core/AddonComponent/Stance.cs
  Core/BotController.cs
  Core/Configurator/FrameConfigurator.cs
  Core/DataFrame/FrameConfig.cs
  Core/Database/AreaDB.cs
  Core/Database/WorldMapAreaDB.cs
  Core/Goals/FollowFocusGoal.cs
  Core/Goals/TargetFocusTargetGoal.cs
  Core/GoalsComponent/CastingHandler.cs
  Core/GoalsFactory/GoalFactory.cs
  Core/Gossip/GossipReader.cs
  Core/Path/RouteInfo.cs
  Core/Talents/TalentReader.cs
  Frontend/Pages/RouteComponent.razor
  README.md
Labels: documentation, bugfix, refactor, enhancement

#387 Addon: [1.7.11] - Feature: `Durability%` - Average worn equipment durability
  Addons/DataToColor/DataToColor.lua
  Addons/DataToColor/DataToColor.toc
  Addons/DataToColor/Query.lua
  Core/Addon/PlayerReader.cs
  Core/Requirement/RequirementFactory.cs
  README.md
Labels: documentation, enhancement

#388 Feature: Rework `NpcNameFinder` - More reliable mouse targeting and skinning due `Interact with Mouseover`
  Core/ClassConfig/ClassConfiguration.cs
  Core/GoalsComponent/NpcNameTargeting.cs
  Core/GoalsComponent/TargetFinder.cs
  Core/Input/ConfigurableInput.cs
  CoreTests/NpcNameFinder/MockWoWProcess.cs
  CoreTests/NpcNameFinder/Test_NpcNameFinder.cs
  CoreTests/Program.cs
  Game/Input/IMouseInput.cs
  Game/Input/WowProcessInput.cs
  README.md
  SharedLib/Extensions/RectangleExt.cs
  SharedLib/NpcFinder/LineOfNpcName.cs
  SharedLib/NpcFinder/NpcNameFinder.cs
  SharedLib/NpcFinder/NpcPosition.cs
Labels: documentation, enhancement, breaking change

#389 Feature: Blacklist rules for `mouseover`
  Addons/DataToColor/Constants.lua
  Addons/DataToColor/DataToColor.lua
  Addons/DataToColor/DataToColor.toc
  Addons/DataToColor/Query.lua
  Core/Addon/AddonReader.cs
  Core/Addon/IMouseOverReader.cs
  Core/Addon/PlayerReader.cs
  Core/AddonComponent/AddonBits.cs
  Core/AddonComponent/UnitsTarget.cs
  Core/BotController.cs
  Core/ClassConfig/ClassConfiguration.cs
  Core/GOAP/GoapAgent.cs
  Core/Goals/ApproachTargetGoal.cs
  Core/Goals/BlacklistTargetGoal.cs
  Core/Goals/FollowRouteGoal.cs
  Core/Goals/PullTargetGoal.cs
  Core/Goals/WalkToCorpseGoal.cs
  Core/GoalsComponent/Blacklist/IBlacklist.cs
  Core/GoalsComponent/Blacklist/MouseOverBlacklist.cs
  Core/GoalsComponent/Blacklist/NoBlacklist.cs
  Core/GoalsComponent/Blacklist/TargetBlacklist.cs
  Core/GoalsComponent/CombatUtil.cs
  Core/GoalsComponent/MountHandler.cs
  Core/GoalsComponent/NpcNameTargeting.cs
  Core/GoalsComponent/ReactCastError.cs
  Core/GoalsComponent/TargetFinder.cs
  Core/GoalsFactory/GoalFactory.cs
  Core/Requirement/RequirementFactory.cs
  CoreTests/NpcNameFinder/MockMouseOverReader.cs
  CoreTests/NpcNameFinder/Test_NpcNameFinder.cs
  Game/Input/WowProcessInput.cs
Labels: refactor, enhancement

#390 Adding npcnamefinder overlay for debug purposes
  CoreTests/CoreTests.csproj
  CoreTests/NpcNameFinder/NpcNameOverlay.cs
  CoreTests/NpcNameFinder/Test_NpcNameFinder.cs
  CoreTests/Program.cs
  CoreTests/app.manifest
  SharedLib/NpcFinder/NpcNameFinder.cs
Labels: work in progress

#391 Addon: [1.7.13] - Throttle combat log cells - React immediately
  Addons/DataToColor/DataToColor.lua
  Addons/DataToColor/DataToColor.toc
  Core/Goals/FollowRouteGoal.cs
Labels: bugfix

#394 Feature: Navigation prefers `World` coordinate system over `Map`
  BlazorServer/Startup.cs
  Core/Addon/AddonReader.cs
  Core/Addon/ConfigAddonReader.cs
  Core/Addon/IAddonReader.cs
  Core/Addon/PlayerReader.cs
  Core/BotController.cs
  Core/Database/AreaDB.cs
  Core/Database/WorldMapAreaDB.cs
  Core/GOAP/Events/CorpseEvent.cs
  Core/GOAP/Events/SkinCorpseEvent.cs
  Core/GOAP/GoapAgent.cs
  Core/Goals/AdhocNPCGoal.cs
  Core/Goals/ApproachTargetGoal.cs
  Core/Goals/CombatGoal.cs
  Core/Goals/FollowRouteGoal.cs
  Core/Goals/LootGoal.cs
  Core/Goals/WalkToCorpseGoal.cs
  Core/Goals/WrongZoneGoal.cs
  Core/GoalsComponent/CombatUtil.cs
  Core/GoalsComponent/MountHandler.cs
  Core/GoalsComponent/Navigation.cs
  Core/GoalsComponent/PlayerDirection.cs
  Core/GoalsComponent/StopMoving.cs
  Core/GoalsComponent/StuckDetector.cs
  Core/GoalsFactory/GoalFactory.cs
  Core/PPather/IPPather.cs
  Core/PPather/LocalPathingApi.cs
  Core/PPather/RemotePathingAPI.cs
  Core/PPather/RemotePathingAPIV3.cs
  Core/Path/DirectionCalculator.cs
  Core/Path/IRouteProvider.cs
  Core/Path/IRouteReceiver.cs
  Core/Path/PointEstimator.cs
  Core/Path/RouteInfo.cs
  Core/Path/Simplify/PathSimplify.cs
  Frontend/Pages/RecordPath.razor
  Frontend/Pages/RouteComponent.razor
  HeadlessServer/Program.cs
  PPather/Graph/PathGraph.cs
  PPather/Search/PPatherService.cs
  PPather/Search/Search.cs
  PathingAPI/Controllers/PPatherController.cs
  PathingAPI/Pages/Index.razor
  PathingAPI/Pages/SearchParameters.razor
  PathingAPI/Pages/Watch.razor
  PathingAPI/PathingAPI.csproj
  PathingAPI/PathingAPI.xml
  PathingAPI/Startup.cs
  SharedLib/Data/WorldMapAreaDB.cs
  SharedLib/Data/WorldMapAreaFactory.cs
  SharedLib/Extensions/VectorExt.cs
  WowheadDB/Herb/Node.cs
  WowheadDB/NPC/NPC.cs
Labels: enhancement

#396 Addon: [1.7.14] - Blacklist: Ignore player controlled units such as pets upon searching for target.
  Addons/DataToColor/DataToColor.lua
  Addons/DataToColor/DataToColor.toc
  Addons/DataToColor/EventHandlers.lua
  Addons/DataToColor/Query.lua
  Core/AddonComponent/AddonBits.cs
  Core/GoalsComponent/Blacklist/MouseOverBlacklist.cs
  Core/GoalsComponent/Blacklist/TargetBlacklist.cs
Labels: enhancement

#399 Fix: Core: FrameConfigurator: Whenever the config process fails due …unable to read class race cell don't let it save the invalid config.
  Core/Configurator/FrameConfigurator.cs
Labels: bugfix

#400 Fix: Addon: [1.7.15]: Other unit deaths can interfere with player kill credit detection. Thus can missing out loot completely!
  Addons/DataToColor/DataToColor.lua
  Addons/DataToColor/DataToColor.toc
  Addons/DataToColor/EventHandlers.lua
Labels: bugfix, enhancement

#401 Addon: [1.7.16] Fix: addon corpse in range and kill credit detection
  Addons/DataToColor/DataToColor.toc
  Addons/DataToColor/EventHandlers.lua
  Addons/DataToColor/Query.lua
  Core/AddonComponent/CombatLog.cs
  Core/AddonComponent/LevelTracker.cs
Labels: bugfix

#402 Feature: `AddonConfig` Allow `CELL_SIZE` change upon install.
  Core/Addon/AddonConfig.cs
  Core/Configurator/AddonConfigurator.cs
  Core/Extensions/RegexExtension.cs
Labels: enhancement

#403 Refactor: `PPather` ADT/WDT types to `readonly struct`
  PPather/Triangles/Data/QuadArray.cs
  PPather/Triangles/Data/SparseFloatMatrix2D.cs
  PPather/Triangles/Data/TrioArray.cs
  PPather/Triangles/MPQTriangleSupplier.cs
  PPather/Triangles/TriangleCollection.cs
  PPather/Triangles/WmoFile.cs
Labels: refactor

#409 Core: AddonConfig: No longer saves `InstallPath` rather uses the currently running `WoWProcess.Path`
  Core/Addon/AddonConfig.cs
  Core/Configurator/AddonConfigurator.cs
  Frontend/Pages/AddonConfiguration.razor
  Game/WoWProcess/WowProcess.cs
Labels: enhancement

#410 Core: `CursorClassifier`: No longer static as it owns resource. `ImageHashing`: better resource management by utilizing shared `Bitmap` and `ArrayPool`
  Core/BotController.cs
  Core/Cursor/CursorClassifier.cs
  Core/Cursor/ImageHashing.cs
  Core/GoalsComponent/NpcNameTargeting.cs
  README.md
Labels: documentation, refactor, enhancement

#411 Refactor: `GoapGoal.State` as array and `PartialState`
  Core/GOAP/GoapAgent.cs
  Core/GOAP/GoapKey.cs
  Core/GOAP/GoapPlanner.cs
  Core/GOAP/PartialState.cs
  Core/Goals/CombatGoal.cs
  Core/Goals/GoapGoal.cs
  Frontend/Pages/GoapGoalView.razor
Labels: refactor, enhancement

#407 Addon: [1.7.17] - Fix: skinning retry attempt skipped - Ignore skinning upon not enough skill level
  Addons/DataToColor/DataToColor.toc
  Addons/DataToColor/EventHandlers.lua
  Core/Addon/GatherSpells.cs
  Core/Addon/PlayerReader.cs
  Core/AddonComponent/UI_ERROR.cs
  Core/Goals/LootGoal.cs
  Core/Goals/SkinningGoal.cs
  Core/Goals/WaitForGatheringGoal.cs
  Core/GoalsComponent/CastingHandler.cs
  Core/GoalsComponent/NpcNameTargeting.cs
Labels: bugfix
